# 因子分析
本篇文章对我国各省市自治区的农业生产情况作因子分析。
## 读取数据
我们从农业生产条件、生产结果和效益出发，选取六项指标。它们分别为：
- X1：乡村劳动力人口（万人）；
- X2：人均经营耕地面积（亩）；
- X3：户均生产性固定资产原值（元）；
- X4：家庭基本纯收入（元）；
- X5：人均农业总产值（千元/人）；
- X6：增加值占总产值比重（%）．

In [186]:
# imports
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
dt = pd.read_csv("FAdata.csv", header=0)
dt.head(-1)

X1     X2        X3       X4      X5    X6
0     66.9   0.93   2972.41  3290.73  2.5250  49.7
1     80.2   1.64   4803.54  2871.62  1.7740  49.6
2   1621.8   2.03   4803.54  2871.81  0.8004  54.0
3    635.4   2.76   2257.66  1499.14  0.5550  56.2
4    514.1  10.17   5834.94  1550.15  0.9051  66.4
5    605.1   2.96   3108.86  2059.35  1.4752  53.1
6    534.2   4.73   4767.51  1940.46  1.1154  63.1
7    494.8   8.24   5573.02  2075.42  1.6283  57.8
8     66.0   1.02   1660.03  4571.81  3.0448  35.6
9   1530.2   1.26   2826.86  2868.33  1.1921  50.6
10  1123.1   0.94   5494.23  3289.07  0.8565  63.3
11  1953.6   1.44   3573.62  1508.24  0.5756  59.2
12   775.8   0.82   2410.05  2295.19  1.1496  62.8
13  1103.2   1.30   2310.98  1804.93  0.6649  59.9
14  2475.1   1.44   3109.11  1989.53  0.8809  55.0
15  2815.8   1.50   3782.26  1508.36  0.5823  58.5
16  1296.5   1.60   2291.60  1754.13  0.8799  62.8
17  2089.3   1.42   2348.72  1719.18  0.5870  64.7
18  1439.8   0.88   3249.61  2928.24  1.0960  59.7
19  1579.9   1.43   3090.17  1590.90  0.5694  64.5
20   165.9   1.35   4454.77  1575.49  0.3535  65.2
21  3903.7   1.08   2870.45  1340.61  0.4443  64.1
22  1376.6   1.18   2282.27  1206.25  0.2892  65.4
23  1642.2   2.42   4025.06  1096.73  0.3456  64.2
24    88.6   2.51  11559.83  1257.71  0.4349  70.4
25  1046.1   2.60   2228.55  1091.96  0.4383  59.7
26   672.0   5.86   2879.36  1037.12  0.4883  57.2
27   137.1   2.62   6725.11  1133.06  0.4096  70.3
28   139.1   4.01   5607.97  1346.89  0.4973  62.5

## 因子分析
### Step 1. 将原始数据标准化

In [187]:
zscore = StandardScaler()
dt = pd.DataFrame(zscore.fit_transform(dt),columns=dt.columns)
print("标准化后均值：\n",dt.mean())
print("\n标准化后方差：\n",dt.var())

标准化后均值：
 X1    3.441691e-16
X2   -1.924387e-16
X3   -3.478699e-16
X4   -2.960595e-17
X5    1.850372e-17
X6   -1.165734e-15
dtype: float64

标准化后方差：
 X1    1.034483
X2    1.034483
X3    1.034483
X4    1.034483
X5    1.034483
X6    1.034483
dtype: float64


### Step 2.建立指标间的相关系数阵R

In [188]:
rij = dt.corr()
print("相关系数阵R：\n", rij)

相关系数阵R：
           X1        X2        X3        X4        X5        X6
X1  1.000000 -0.332548 -0.375278 -0.176408 -0.395522  0.140047
X2 -0.332548  1.000000  0.350943 -0.300054 -0.001433  0.164717
X3 -0.375278  0.350943  1.000000 -0.229102 -0.129731  0.410019
X4 -0.176408 -0.300054 -0.229102  1.000000  0.789003 -0.723103
X5 -0.395522 -0.001433 -0.129731  0.789003  1.000000 -0.794783
X6  0.140047  0.164717  0.410019 -0.723103 -0.794783  1.000000


### Step 3. 求R的特征根和特征向量

In [189]:
data = np.array(rij)
eigval, eigvec = np.linalg.eig(data)
eigval.shape[0]
contribute = np.zeros(eigval.shape[0])
for i in range(eigval.shape[0]):
    contribute[i] = np.sum(eigval[0:i+1])/np.sum(eigval)
print("累积贡献率：\n",contribute)
eigvec = pd.DataFrame(eigvec[:,0:3],columns=["alpha1","alpha2","alpha3"])
eigvec["alpha3"] = -1*eigvec['alpha3']
print("前三个特征值对应的特征向量：\n",eigvec)

累积贡献率：
 [0.45988503 0.75066258 0.86989018 0.9436219  0.96385794 1.        ]
前三个特征值对应的特征向量：
      alpha1    alpha2    alpha3
0  0.136631 -0.626487 -0.171035
1  0.167626  0.523707 -0.746427
2  0.243657  0.524490  0.547956
3 -0.543835  0.015423  0.246166
4 -0.541958  0.240158 -0.045500
5  0.551715  0.015511  0.225100


由于前三个特征值的贡献率已达到 85\%, 因此我们取前三个向量
### Step 4. 计算因子载荷矩阵

In [190]:
A = pd.DataFrame(np.dot(eigvec,np.diag(np.sqrt(eigval[0:3]))),columns=["a1","a2","a3"])
A["h2"] = np.sum(A**2,axis=1)
A

a1        a2        a3        h2
0  0.226960 -0.827501 -0.144660  0.757195
1  0.278447  0.691743 -0.631323  0.954610
2  0.404743  0.692776  0.463457  0.858548
3 -0.903374  0.020371  0.208206  0.859849
4 -0.900256  0.317215 -0.038483  0.912566
5  0.916463  0.020488  0.190388  0.876572

### step 5. 因子 varimax 旋转

In [198]:
def varimax(data,var1,var2):
    uj = (data.iloc[:,var1]/np.sqrt(data.iloc[:,-1]))**2 - (data.iloc[:,var2]/np.sqrt(data.iloc[:,-1]))**2
    vj = 2*(data.iloc[:,var1]/np.sqrt(data.iloc[:,-1])) * (data.iloc[:,var2]/np.sqrt(data.iloc[:,-1]))
    A = np.sum(uj)
    B = np.sum(vj)
    C = np.sum(uj**2-vj**2)
    D = np.sum(2*uj*vj)
    p = uj.shape[0]
    phi = np.tanh((D-2*A*B/p)/(C-(A**2-B**2)/p))/4
    print(phi)
    T = np.matrix([[np.cos(phi),-np.sin(phi)],[np.sin(phi),np.cos(phi)]])
    print(T)
    print(np.dot(T,T.transpose()))
    data.iloc[:,[var1,var2]] = np.dot(data.iloc[:,[var1,var2]],T)
    data["h2"] = np.sum(data.iloc[:,:3]**2,axis=1)

varimax(A,0,1)
print(A)
varimax(A,0,2)
print(A)
varimax(A,1,2)
print(A)

-3.5772856368055786e-08
[[ 1.00000000e+00  3.57728564e-08]
 [-3.57728564e-08  1.00000000e+00]]
[[1.00000000e+00 2.64027032e-24]
 [2.64027032e-24 1.00000000e+00]]
         a1        a2        a3        h2
0  0.327733 -0.764436 -0.255782  0.757195
1  0.206206  0.806323 -0.511793  0.954610
2  0.308884  0.657395  0.575300  0.858548
3 -0.903366 -0.115917  0.174190  0.859849
4 -0.930878  0.212977 -0.025943  0.912566
5  0.903235  0.097633  0.226289  0.876572
-1.35157407824267e-07
[[ 1.00000000e+00  1.35157408e-07]
 [-1.35157408e-07  1.00000000e+00]]
[[ 1.00000000e+00 -1.28400405e-23]
 [-1.28400405e-23  1.00000000e+00]]
         a1        a2        a3        h2
0  0.327733 -0.764436 -0.255782  0.757195
1  0.206206  0.806323 -0.511793  0.954610
2  0.308884  0.657395  0.575300  0.858548
3 -0.903366 -0.115917  0.174190  0.859849
4 -0.930878  0.212977 -0.025943  0.912566
5  0.903235  0.097633  0.226289  0.876572
4.6658361612757676e-08
[[ 1.00000000e+00 -4.66583616e-08]
 [ 4.66583616e-08  1.0000000

# Step 6. 因子得分

In [199]:
B = np.dot(A.iloc[:,0:3].transpose(),np.linalg.inv(rij))
B

array([[ 0.14282762,  0.07066788,  0.08450274, -0.33234546, -0.34457629,
         0.32276081],
       [-0.42576225,  0.53363429,  0.30946821, -0.0702019 ,  0.14881837,
         0.00998812],
       [-0.26636158, -0.81022582,  0.70427413,  0.2768544 , -0.03897366,
         0.27750372]])

In [200]:
np.sum(abs(np.dot(B,dt.transpose())),axis=0)

array([2.76378234, 2.67108403, 1.23538003, 0.98001904, 5.10048403,
       1.60336757, 1.31197861, 3.89145731, 3.78269223, 1.80313989,
       2.32661547, 1.36544963, 1.1870663 , 0.89107718, 1.60380938,
       2.06014875, 1.01953125, 1.93117349, 1.81901119, 1.32626343,
       1.67368109, 3.64289754, 1.82015722, 1.48715028, 5.93719805,
       1.70934554, 3.18525926, 3.29408635, 1.80827246, 1.96652295])

In [181]:
A = np.array([[0.2433,-0.8236,-0.1564,0.7621],
 [0.2718,0.6954,0.6366,0.9629],
[0.4035,0.6957,0.4529,0.8520],
[-0.9103,0.0202,0.1961,0.8675],
[-0.9089,0.3057,-0.0356,0.9210],
[0.9086,0.0296,0.1920,0.8634]])
A = pd.DataFrame(A,columns=["a1","a2","a3","h2"])
A

a1      a2      a3      h2
0  0.2433 -0.8236 -0.1564  0.7621
1  0.2718  0.6954  0.6366  0.9629
2  0.4035  0.6957  0.4529  0.8520
3 -0.9103  0.0202  0.1961  0.8675
4 -0.9089  0.3057 -0.0356  0.9210
5  0.9086  0.0296  0.1920  0.8634