## 自定义层
### 不带参数的层

In [1]:
import torch
import torch.nn.functional as F
from torch import nn 

class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()
    
    def forward(self, X):
        return X - X.mean()

layer = CenteredLayer()
layer(torch.FloatTensor([1, 2, 3, 4, 5]))

tensor([-2., -1.,  0.,  1.,  2.])

In [2]:
net = nn.Sequential(nn.Linear(8, 128), CenteredLayer())
Y = net(torch.rand(4, 8))
Y.mean(), Y.shape

(tensor(3.7253e-09, grad_fn=<MeanBackward0>), torch.Size([4, 128]))

### 带参数的层

In [4]:
class MyLinear(nn.Module):
    def __init__(self, in_units, units):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_units, units))
        self.bias = nn.Parameter(torch.randn(units,))

    def forward(self, X):
        linear = torch.matmul(X, self.weight.data) + self.bias.data
        return F.relu(linear)
    
linear = MyLinear(5, 3)
linear.weight, linear(torch.rand(2, 5))

(Parameter containing:
 tensor([[ 0.8858,  2.6096,  1.6312],
         [ 0.4434,  0.2338,  1.0514],
         [ 0.6883, -0.3526,  0.4423],
         [ 0.2114, -1.3852,  1.7254],
         [-0.3068,  0.4767, -0.6848]], requires_grad=True),
 tensor([[3.4749, 1.9908, 1.0851],
         [4.0082, 1.9620, 1.1850]]))

In [16]:
net = nn.Sequential(MyLinear(64, 8), MyLinear(8, 1))
net(torch.rand(2, 64))

tensor([[12.0133],
        [ 1.0035]])